update package, Register logic, methods' name, locations' name.
JimCVR/vertx-kafka pull request #1
Opened 2024-01-11 10:51 UTC by JimCVR

2024-01-11 10:54 UTC, dotxoa requested changes

2024-01-11 10:54 UTC, dotxoa commented on src/main/java/io/reactorsolutions/actors/Main.java
> +    vertx.deployVerticle(ServerVerticle.class.getName());
No debería crearse primero el enemy y luego el server?

2024-01-11 10:54 UTC, dotxoa commented on src/main/java/io/reactorsolutions/actors/singleton/Register.java
> +package io.reactorsolutions.actors.singleton;
No creo que `singleton` sea el mejor nombre de paquete. Busca algo más representativo

2024-01-11 10:54 UTC, dotxoa commented on src/main/java/io/reactorsolutions/actors/verticles/EnemyVerticle.java
> +  public void start() {
Cuál es la diferencia entre el método `start` y el método `init` de un vértice?

2024-01-11 11:20 UTC, JimCVR commented on src/main/java/io/reactorsolutions/actors/verticles/EnemyVerticle.java
> +  public void start() {
El metodo init inicializa el vertice cuando se hace el deployVerticle, y el start ejecuta el codigo de su body, una vez que se hace deploy del verticle. El deployVerticle, llama a ambos metodos cuando quiere levantar uno.

 
![Captura de pantalla 2024-01-11 121859](https://github.com/JimCVR/vertx-kafka/assets/80890402/1db4570d-2157-4990-9685-7387cb9bd325)

2024-01-11 11:33 UTC, JimCVR commented on src/main/java/io/reactorsolutions/actors/Main.java
> +    vertx.deployVerticle(ServerVerticle.class.getName());
Se crean a la vez porque se lanzan 2 hilos independientes:
![Captura de pantalla 2024-01-11 122943](https://github.com/JimCVR/vertx-kafka/assets/80890402/258b0578-5511-4d68-a21b-b3404df9cb93)
 
Si se busca crear primero el enemy y luego el server, se debe añadir nueva logica, para retrasar la creación del servidor con respecto a la del enemigo

2024-01-12 11:54 UTC, dotxoa commented on src/main/java/io/reactorsolutions/actors/verticles/EnemyVerticle.java
> +  private final int maxHp = 200;
Do it static and write it as `MAX_HP`

2024-01-12 11:54 UTC, dotxoa commented on src/main/java/io/reactorsolutions/actors/verticles/WarriorVerticle.java
>      username = ctx.config().getString("username");
`var config = ctx.config()` reuse it

2024-01-12 12:29 UTC, dotxoa approved these changes

2024-01-12 15:12 UTC, dotxoa commented on src/main/java/io/reactorsolutions/vertx_kafka/verticles/BrolyVerticle.java
>    //Se envian y reciben JSON de broly
Remove spanish comments

2024-01-12 15:34 UTC, merged